### ISSUE TITLE
remove regular expression substitution in _instance_name

### ISSUE THREAD

**Issue by lucabello** [canonical/grafana-agent-operator#100]
### Enhancement Proposal

When returning the [_instance_name](https://github.com/canonical/grafana-agent-operator/blob/main/src/grafana_agent.py#L775-L787), we currently do a regex substitution to only keep ASCII character in label values.

However, according to the [docs we link to](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), it explicitly mentions that label values can be unicode character.

**Comment by sabaini** [comment]
Heya, for addtl context I believe this was introduced [here](https://github.com/canonical/grafana-agent-operator/pull/63)  in the course of fixing [#60](https://github.com/canonical/grafana-agent-operator/issues/60)

**Comment by sed-i** [comment]
Yep, probably a confusion on my part. To summarize the doc:
- Metric name: `[a-zA-Z_:][a-zA-Z0-9_:]*`
- Label name (key): `[a-zA-Z_][a-zA-Z0-9_]*`
- Label value: may contain any Unicode characters
