### ISSUE TITLE
grafana-agent charm based on Noble

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-operator#155]
### Enhancement Proposal

We need [grafana-agent charm based on Noble](https://matrix.to/#/!nHXpRkcSNJHlHdUGbQ:ubuntu.com/$twAA6KOlxwB9StUn8_E7-3yS45TwHVw_19t0sANDxIk?via=ubuntu.com&via=matrix.org).

Refs:
- https://discourse.charmhub.io/t/how-build-charm-for-multiple-bases-with-charmcraft-3-1/15266/4

**Comment by mthaddon** [comment]
Any news on this one? It'll be needed for us as part of deploying the new version of the NTP charm (with NTS).

**Comment by sed-i** [comment]
Sounds like you've been involved with 24.04 for other things.
Do you happen to have an example for how other charms transitioned to the new charmcraft.yaml single-base syntax?

We could release manually a one-off, but just wondering if someone already solved this.

**Comment by mthaddon** [comment]
The NTP charm is new, and only supports one series (noble), so I don't have experience with that aspect unfortunately. I've asked the question [here](https://discourse.charmhub.io/t/how-build-charm-for-multiple-bases-with-charmcraft-3-1/15266/4).
