### ISSUE TITLE
`--trust` is too high privilege for a machine charm

### ISSUE THREAD

**Issue by nobuto-m** [canonical/grafana-agent-operator#21]
### Bug Description

The document suggests to add `--trust` when deploying the charm.

https://github.com/canonical/grafana-agent-operator/blob/49abf15ffcde20d02961118f921c34565084a310/README.md#L36-L40

I don't think that's a necessary privilege since grafana agent doesn't have to access to credentials of substrates. e.g. MAAS credentials.

If it's really necessary, we should add some clarifications around it.

### To Reproduce

N/A - as a documentation issue

### Environment

With MAAS provider in mind.

### Relevant log output

```shell
N/A
```

**Comment by simskij** [comment]
Yes, trust is not needed for the machine subordinate. Docs need to be updated accordingly.
