### ISSUE TITLE
metrics-endpoint (interface: prometheus_scrape) is not implemented

### ISSUE THREAD

**Issue by nobuto-m** [canonical/grafana-agent-operator#25]
### Bug Description

Although the README states that `metrics-endpoint` is supposed, there is no metadata definition in the charm to use it.
https://github.com/canonical/grafana-agent-operator/blob/49abf15ffcde20d02961118f921c34565084a310/README.md#L48-L59

The downside of not having the implementation is that ceph-mon for example has to be scraped by prometheus so managing firewall policy, etc. is challenging than having grafana-agent with remote_write in the middle.

More context: https://bugs.launchpad.net/charm-ceph-mon/+bug/2041167

### To Reproduce

1. deploy ceph-mon and grafana-agent charm in MAAS provider
2. relate those two

### Environment

```
ceph-mon           17.2.6   active      3  ceph-mon                quincy/stable  185  no       Unit is ready and clustered
grafana-agent               active     13  grafana-agent           latest/edge     20  no       
```

### Relevant log output

```shell
$ juju integrate ceph-mon grafana-agent
ERROR cannot add relation "grafana-agent:juju-info ceph-mon:juju-info"
relation grafana-agent:juju-info ceph-mon:juju-info (already exists): 

$ juju integrate ceph-mon grafana-agent:metrics-endpoint
ERROR application "grafana-agent" has no "metrics-endpoint" relation
```

**Comment by nobuto-m** [comment]
Not sure which side needs work though. Looks like the grafana-agent charm has a completely new interface as `cos_agent` so it's either:

- Document should be updated by removing the mention to metrics-endpoint, and every single charm out there should implement the `cos_agent` relation.
- Implement `metrics-endpoint` relation in grafana-agent charm so existing charms with `metrics-endpoint` do not require modifications

I haven't looked into the detail of the difference of those two relations though.

https://github.com/canonical/grafana-agent-operator/blob/49abf15ffcde20d02961118f921c34565084a310/metadata.yaml#L38-L51

**Comment by simskij** [comment]
Hi Nobuto,

Thank you for the issue! Yes, the docs need to be updated. We quite recently split the two different charms from a prior monorepo.

There are still some documentation that needs an update as a result of the split. But you are correct, cos_agent is the interface that should be used by **machine charms** that wish to natively integrate with the grafana agent subordinate.

**Comment by simskij** [comment]
Closing this as `cos-agent` will be the only supported relation between principals and the GA subordinate. `ceph-mon`now also correctly implements the relation, thanks @sabaini!
