### ISSUE TITLE
Graphs will have no data when zoomed in due to misalignment when `$__rate_interval` is used

### ISSUE THREAD

**Issue by nobuto-m** [canonical/grafana-agent-operator#26]
### Bug Description

10 graphs in the node exporter dashboard are missing due to "no data" https://github.com/canonical/grafana-agent-operator/issues/23

However, 43 additional graphs will be missed when it's zoomed into say "Last 15 minutes". I think this is due to the misalignment in `$__rate_interval`. `scrape interval` in the data source config is not set and it has 15s as the default value. However, Prometheus in COS uses 1m as the global scrape_interval so `$__rate_interval` won't be properly calculated if I'm not mistaken.

ref: https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

[zoomed in to 15 min]
![image](https://github.com/canonical/grafana-agent-operator/assets/4356209/7a824554-7843-4aea-b2f1-213930f10ff0)

[after manually putting >1m (the scrape_interval) to the `Min step`]
![image](https://github.com/canonical/grafana-agent-operator/assets/4356209/3bb33490-d3b4-4023-ad9e-75530e93d13a)

[scrape interval is not set in the data source config]
![image](https://github.com/canonical/grafana-agent-operator/assets/4356209/53e381b6-cf89-4fff-aca0-0a9728e24afa)

### To Reproduce

With MAAS provider, deploy the grafana-agent charm onto another charm, and relate it to COS. Then zoom into 15 min range in the Grafana node-exporter dashboard.

### Environment

grafana-agent           latest/edge     20

### Relevant log output

```shell
N/A
```

**Comment by nobuto-m** [comment]
Moved to: https://github.com/canonical/prometheus-k8s-operator/issues/543

**Comment by simskij** [comment]
@nobuto-m reopening this as it feels like a more appropriate place to have the conversation, as the agent subordinate charm won't have the option of using the scrape config charm inbetween.

**Comment by nobuto-m** [comment]
Hmm, what kind of actions are expected in the grafana-agent charm for this issue?

**Comment by marcusboden** [comment]
Hi, we're seeing the issue with one of our customers. 
I've manually set the scrape_interval to 15s to test, which does the job but is not very permanent. It would be good to create a fix, similar to the k8s charm.

**Comment by sed-i** [comment]
A config option for setting scrape interval was added in #103.
Do you still have this issue @nobuto-m  @marcusboden ?

**Comment by nobuto-m** [comment]
It wasn't me who reopened this issue since I closed it to move to https://github.com/canonical/prometheus-k8s-operator/issues/543

**Comment by sed-i** [comment]
Thanks for the update, so closing for now.
