### ISSUE TITLE
Latest revision (24) isn't published for jammy

### ISSUE THREAD

**Issue by samuelengineer** [canonical/grafana-agent-operator#38]
The latest revision available on charmhub is 24, but that revision isn't published for jammy.  The latest revision with jammy support is 23, but that contains a regression that was fixed in revision 24.  Could revision 24 be built and publish for jammy please?  Thanks.

**Comment by simskij** [comment]
Hi!

`r26`, targeting `22.04`, has now been released to `edge`. We have [an issue open in our CI repo](https://github.com/canonical/observability/issues/123) for the bug that resulted in this discrepancy.

Best,
Simon
