### ISSUE TITLE
Loki alert rules contain ﻿invalid label

### ISSUE THREAD

**Issue by cbartz** [canonical/grafana-agent-operator#55]
### Bug Description

Loki alert rules defined by a charm included in the grafana agent and those defined in the grafana agent contain the label `juju_charm`, although the logs are transmitted without this label. Furthermore, the job label is not present for the logs, so the alert rules defined in the grafana-agent are incorrect.

### To Reproduce

1. `juju deploy github-runner` (or any compatible machine charm)
2. `juju integrate github-runner grafana-agent`

Go to the dashboard.
![Screenshot from 2024-02-02 09-10-15](https://github.com/canonical/grafana-agent-operator/assets/4182921/9aaa99b8-5fef-4791-a735-d94c858a4b98)
![Screenshot from 2024-02-02 09-12-15](https://github.com/canonical/grafana-agent-operator/assets/4182921/fc1b2ec5-0a7f-4c2c-85d4-4780db879a0e)
![image](https://github.com/canonical/grafana-agent-operator/assets/4182921/9b2fae24-2b2d-4828-a351-c9314573b980)

### Environment

reproduced on multipass and openstack cloud with grafana-agent rev 37

### Relevant log output

```shell
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Reading <property object at 0x7f05a0f02700> rule from /var/lib/juju/agents/unit-grafana-agent-44/charm/prometheus_alert_rules/juju_gh-runner_eb824e40_grafana-agent.rules
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: updated alert rules file /var/lib/juju/agents/unit-grafana-agent-44/charm/loki_alert_rules/juju_gh-runner_eb824e40_github-runner.rules
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Could not locate cos-tool at: "cos-tool-amd64"
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Skipping injection of juju topology as label matchers
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: `cos-tool` unavailable. Leaving expression unchanged: count_over_time(({filename=~"/var/log/juju/unit-.*"} |= "Failed to start the timer for reconciliation event")[1h]) > 0

unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Reading alert rule from /var/lib/juju/agents/unit-grafana-agent-44/charm/loki_alert_rules/juju_gh-runner_eb824e40_github-runner.rules
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: `cos-tool` unavailable. Leaving expression unchanged: count_over_time(({job=~".+"})[30s]) > 100

unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Reading alert rule from /var/lib/juju/agents/unit-grafana-agent-44/charm/loki_alert_rules/grafana_agent_high_rate.rule
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: `cos-tool` unavailable. Leaving expression unchanged: count_over_time({job="varlogs"} |= "error" [1h]) > 100
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: Reading alert rule from /var/lib/juju/agents/unit-grafana-agent-44/charm/loki_alert_rules/high_error_rate.rule
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: updated dashboard file /var/lib/juju/agents/unit-grafana-agent-44/charm/grafana_dashboards/juju_github_self-hosted_runner_metrics-cos-agent-github-runner-98.json
unit-grafana-agent-44: 09:01:33 DEBUG unit.grafana-agent/44.juju-log cos-agent:98: updated dashboard file /var/lib/juju/agents/unit-grafana-agent-44/charm/grafana_dashboards/juju_github_self-hosted_runner_metrics_(long-term)-cos-agent-github-runner-98.json
```

**Comment by lucabello** [comment]
Apparently, we only add the `job` label for scrape configs that come from the snap slots, [here](https://github.com/canonical/grafana-agent-operator/blob/main/src/charm.py#L495C27-L495C45). We should likely add that `job` label [here](https://github.com/canonical/grafana-agent-operator/blob/main/src/charm.py#L388) as well. This should fix the issue :)

**Comment by cbartz** [comment]
@lucabello  Is there a timeframe for when this will be fixed? This currently prevents the definition of loki alert rules when using the grafana agent.
