### ISSUE TITLE
Missing copyright owner and date in Apache license

### ISSUE THREAD

**Issue by srunde3** [canonical/grafana-agent-operator#62]
https://github.com/canonical/grafana-agent-operator/blob/7f3cfb08a71c5cab93d92871087358d4eb9ee719/LICENSE#L189

**Comment by mmkay** [comment]
Hi @srunde3, thank you for the feedback! We do have a copyright notice on our code as mentioned in the linked section in the LICENSE (see, for instance, https://github.com/canonical/grafana-agent-operator/blob/7f3cfb08a71c5cab93d92871087358d4eb9ee719/src/grafana_agent.py#L1 as a reference). Feel free to report if you see any of our code files failing to include that, thanks!
