### ISSUE TITLE
Always observe config-changed, in addition to whatever is passed as refresh_events

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-agent-operator#71]
We need to always observe config-changed. And document here that there is no need to pass config-changed nor upgrade-charm as refresh events.

- config-changed is currently observed only if `refresh_events` is None.
- I do not see any observer for `start`

Given the above I think we need to always observe config-changed. And document here that there is no need to pass config-changed nor upgrade-charm as refresh events.

_Originally posted by @sed-i in https://github.com/canonical/grafana-agent-k8s-operator/pull/122#discussion_r1131913481_

**Comment by simskij** [comment]
It kind of makes sense that we don't include events when the charm choses to override the refresh events. If you don't, you get the defaults. If you do, you'll need to be explicit about which events you want to act as triggers. Closing without action.
