### ISSUE TITLE
AppArmor log flooding with grafana-agent

### ISSUE THREAD

**Issue by adilcan** [canonical/grafana-agent-operator#83]
### Bug Description

Hi,

After deploying the grafana-agent charm (during the COS installation), there is a significant flooding of logs in /var/log/audit/audit.log on bare metal servers running LXD containers. The logs are predominantly filled with apparmor="DENIED" messages.

The log entries are temporarily discarded by executing the below command:

`echo -n quiet_denied > /sys/module/apparmor/parameters/audit`

Please let me know if anything else is needed!

### To Reproduce

1. install and initialize lxd 5.20 on a focal host.
2. bootstrap a juju 2.9.46 environment.
3. install and enable auditd 1:2.8.5-2ubuntu6.
4. deploy the grafana-agent charm.
5. check /var/log/audit/audit.log.

### Environment

OS: Ubuntu 20.04.6 LTS 5.4.0-155-generic x86_64

juju version: 2.9.46
grafana-agent charm: latest/stable

related snaps:
grafana-agent        0.35.4         16     latest/stable  0x12b        -
lxd                  5.20-f3dd836   27049  5.20/stable    canonical**  -

related debs:
apparmor                              2.13.3-7ubuntu5.2
auditd                                1:2.8.5-2ubuntu6

### Relevant log output

```shell
type=AVC msg=audit(...): apparmor="DENIED" operation="capable" namespace="root//lxd-juju-..._<var-snap-lxd-common-lxd>" profile="snap.grafana-agent.grafana-agent" pid=2365835 comm="agent" capability=2 capname="dac_read_search"
type=AVC msg=audit(...): apparmor="DENIED" operation="capable" namespace="root//lxd-juju-..._<var-snap-lxd-common-lxd>" profile="snap.grafana-agent.grafana-agent" pid=... comm="agent" capability=2 capname="dac_read_search"
type=AVC msg=audit(...): apparmor="DENIED" operation="capable" namespace="root//lxd-..._<var-snap-lxd-common-lxd>" profile="snap.grafana-agent.grafana-agent" pid=... comm="agent" capability=2 capname="dac_read_search"
type=AVC msg=audit(...): apparmor="DENIED" operation="capable" namespace="root//lxd-..._<var-snap-lxd-common-lxd>" profile="snap.grafana-agent.grafana-agent" pid=... comm="agent" capability=2 capname="dac_read_search"
```

**Comment by sed-i** [comment]
Duplicates #52.

**Comment by dstathis** [comment]
Closing this as a dup.
